### ISSUE TITLE
DEC - handle multiple entry points

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon-ibex#105]
Currently what we do when we generate DECs is to search for a possible dangling edge.
Given that we found such, we check if there is some other rule application that is still able to translate it given that we apply the current rule.
The problem is now that there is not necessarily just one possible candidate edge in another rule but possibly many of them. 
The question is now what to do with them.
The current approach just takes one of these candidates and checks for them which might not be so clever in case that src- or trg-nodes also have attribute constraints that have to be fulfilled.

**Comment by anthonyanjorin** [comment]
Err...  you have to check all candidates right?

If all of them can be ruled out statically then you generate a DEC NAC just like today, if not you generate an application condition that checks for at least one of the required conditions for the determined candidates.

I don't understand the problem (what this issue discusses) :)

And what does this have to do with entry points?

**Comment by Arikae** [comment]
Well if you have some application condition then you have to generate those calls for each possible combination of your entry point (which is the to-be-translated node which is connected to the dangling edge). That is something we might wanna do in the future but for the moment this should suffice.
The idea is that we keep this in mind but since there is a huge optimization potential, we want to get the first version running before we extend it to the more general case.
This issue is more of a reminder for me

**Comment by anthonyanjorin** [comment]
I'm not sure if it is helpful to think in terms of "entry points".  

Currently, I see things in terms of patterns like this:

If a certain rule is to be applied (we don't have any entry points really), then a certain *set* of potential dangling points can be determined for the rule application.

For all dangling edges in this set, all candidates for translating the dangling edges should be determined.   If there are no candidates then a normal DEC NAC should be generated.  If candidates can be determined then a complex application condition should be created ensuring (to a certain extent) that at least one of the candidates has a chance (or blocking the rule application if none of them have a chance).

What does this have to do with entry points?  I still don't understand the point (or the current simplification)...

**Comment by anthonyanjorin** [comment]
FYI @erhanleblebici

**Comment by Arikae** [comment]
Maybe we both have a different understanding of what an entry point is. For me an entry point is a node which gets translated in my current rule. Given this node, I try to find an edge that would remain untranslated. If I find such an edge, I take the "entry point" as well the opposite node of the edge that I just found and insert it into the patterns which could possibly translate my edge. What we are currently NOT doing is to call those patterns with every possible combination of our entry and opposite (DEC) node which is something we are going to do in the near future but just not today so that I can test the rest of the implementation before making everything more complicated :)

**Comment by anthonyanjorin** [comment]
I don't understand this issue and I'm not sure if it is even relevant for filter NACs.

This can be revisited if we have failing tests that indicate what is going wrong (and if something can really go wrong).
