### ISSUE TITLE
OR invocation in Democles

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon-ibex#110]
Is it possible to have a pattern construct in democles where the invocations are combined using OR instead of AND? As far as I know, I could implement it myself, although I'm not sure if that would be unproblematic. The question is if such a construct already exists.

**Comment by anthonyanjorin** [comment]
@gervarro:  is this perhaps the reason why a pattern can have multiple bodies?  Are all bodies ored to check if the pattern matches?

We couldn't find such an example in the train benchmark...

**Comment by gervarro** [comment]
> is this perhaps the reason why a pattern can have multiple bodies? Are all bodies ored to check if the pattern matches?

Yes. This is exactly the reason.

> We couldn't find such an example in the train benchmark...

No surprise. This has been a completely untested / unused feature, so do not be surprised if you find bugs, although it is rather easy to support the concept (compared to pattern invocation and the like).
