### ISSUE TITLE
Improvements of pattern vis

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#116]
1.  Local variables 
2.  Parameter passing for pattern invocation
3.  __or__ patterns

**Comment by Arikae** [comment]
4. better distinction between positive and negative invocations

**Comment by anthonyanjorin** [comment]
How should local variables look like?  Different colour?  Grey perhaps?

**Comment by anthonyanjorin** [comment]
How would a better distinction look like?  Red edge?

**Comment by anthonyanjorin** [comment]
(2) could be realised by adding edges showing which variables were passed as which variables (we could then remove the edges connecting the patterns and change the border of the invoked pattern to indicate positive/negative).

**Comment by Arikae** [comment]
(1) I saw that currently signature elements are visualized with a capital C and virtual nodes that are only known from edges have a capital V. Maybe we could introduce a L?

**Comment by Arikae** [comment]
(2) I guess this could become very confusing when the pattern becomes bigger but I guess we could give it a try

**Comment by Arikae** [comment]
(3) still not sure if we need this (or not the vis)

**Comment by Arikae** [comment]
(4) blue and red?

**Comment by anthonyanjorin** [comment]
True...  (3) could be achieved just by selecting each _body_ in the tree editor (and visualising each _or_ branch in that manner)

**Comment by anthonyanjorin** [comment]
So:  (1) Local variables are now visualised with an L, (2) Links are drawn between variables to indicate parameter passing for invoked patterns, (3) or patterns can be handled as you now have to choose the body to be visualised, (4) the edges used for negative pattern invocation are different and the background of the invoked pattern is also grey as opposed to white for positive pattern invocations.

To handle patterns with multiple bodies I now visualise only symbolic parameters for invoked patterns (i.e., all further details such as multiple bodies or local variables are hidden and can only be seen by choosing the respective pattern body in the editor).
