### ISSUE TITLE
Broken EEnumLiteral with generated Code

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon-ibex#125]
When we only operate on ecore models, we can use enums.
The problem occurs when we generate code from these ecore models.
Somehow the literals are instantiated as general instances of EEnumLiteral which leads to a serious failure when we try to cast it to a specific implementation of EEnumLiteral.

**Comment by anthonyanjorin** [comment]
Any ideas how we can fix this?  I don't understand why we have this problem

**Comment by Arikae** [comment]
Nope, we neither. I just ran into this problem when I generated code from an existing .ecore and used the newly generated project instead. I have absolutely no idea why it generates ConcreteEnumLiterals as instances of the generic class EENumLiteral....

**Comment by SaschaEdwinZander** [comment]
EEnumLiterals have the method getInstance() which returns the real Enumeration as org.eclipse.emf.common.util.Enumerator. This Enumerator can be used in the EObject.eSet() without the failure.

**Comment by anthonyanjorin** [comment]
@Arikae @erhanleblebici Could we transfer this fix to master?
