### ISSUE TITLE
Redundant Protocol-NACs in Democles patterns

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#128]
An example is attached, I marked in the pdf-file the redundant part.

[ibexpatterns1.pdf](https://github.com/eMoflon/emoflon-ibex/files/889376/ibexpatterns1.pdf)

**Comment by Arikae** [comment]
These marked pattern invocations were not redundant but falsely implemented. (Copy-Paste error)
There we check if the elements that are context have already been marked instead of checking that "green" elements have not yet been marked.
