### ISSUE TITLE
Inter-rule pattern invocations for DEC are missing in Democles patterns

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#129]
cf. the annotation in the pdf file
[ibexpatterns1.pdf](https://github.com/eMoflon/emoflon-ibex/files/890326/ibexpatterns1.pdf)

**Comment by Arikae** [comment]
Should be fixed

**Comment by Arikae** [comment]
Minor addition - as for now the fix is only in the PatternMapping branch
