### ISSUE TITLE
Join Failed as runtime exception

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#136]
Hi Greg,

for a simple pattern network we are getting a `Join Failed` exception and do not understand what is wrong.

Please find a diagram* of the relevant pattern network attached, together with the patterns file and all models.

Thanks!
Tony

(*)  Patterns are depicted as packages, variables as classes with V, local variables as classes with L.  Negatively invoked patterns have a grey background.  Parameter bindings are indicated with connectors and lines (which are dashed for negative pattern invocations).

![patterncausingjoinexception](https://cloud.githubusercontent.com/assets/6302793/24858867/5751eff4-1dee-11e7-9c82-0d2ca256f819.png)
[patternsAndModels.zip](https://github.com/eMoflon/emoflon-ibex/files/909809/patternsAndModels.zip)

**Comment by anthonyanjorin** [comment]
This might be related to #108. I'm not absolutely sure but now and then it seems to work without throwing an exception.

**Comment by gervarro** [comment]
I wanted to test this issue as well, but the model did not contain any families, consequently, there were no matches for patterns containing a `Family`. Could you please send me a model with families?

A `JoinFailedException` is typically thrown, if the mapping of variables to match positions is screwed up, and I have not seen this kind of exception for a while. The `FatherToMaleRule__CONTEXT_SRC` rule contains two constraints, although `families` and `familiesInverse` seem to be the same bidirectionally navigable reference, so it would be enough to list this constraint only once (with an arbitrary direction). However, the pattern matcher should definitely be more robust in this case.

**Comment by anthonyanjorin** [comment]
@FStolte Is this still relevant?  Could you provide some models?

**Comment by gervarro** [comment]
This is still relevant, and now I know what the problem is.

**Comment by anthonyanjorin** [comment]
I'll close this issue as we now have tests that fail and document this in a reproducible manner.
