### ISSUE TITLE
Configurable Filter NAC generation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#139]
Filter NACs (DEC NACs) are useful but can sometimes be restrictive or inefficient (and for some example unnecessary). 

We should introduce a config Parameter for sync that should enable choosing between:  (1) no filter NACs at all, (2) simple filter NACs (as in eMoflon), and (3) advanced filter NACs (currently implemented).

**Comment by erhanleblebici** [comment]
this is now configurable by setting the NoDECsPatterns::strategy attribute. It has no DEC-check (NONE) per default and is only accessible to developers.
You might choose to  pass its value via constructors of higher-level stub classes for the user.
