### ISSUE TITLE
[ibex_viatra] Can't resolve language.ecore

### ISSUE THREAD

**Issue by SaschaEdwinZander** [eMoflon/emoflon-ibex#146]
I am using a TGG to transform other TGGs. The loading of the TGG model (..../language.ecore) is working, but the Types of the TGG aren't resolved. They are proxies and using EcoreUtil.resolveAll() is not solving the problem.

The workaround is this hack:

```
...
EPackage tggEPackage = LanguagePackage.eINSTANCE;
Registry.INSTANCE.put("platform:/plugin/org.emoflon.ibex.tgg.core.language/model/Language.ecore", tggEPackage);		
EcoreUtil.resolveAll(rs); //rs is a ResourceSet
```
 
Normally it should work with  `LanguagePackage.eINSTANCE.getName();` to register and resolve the meta-model.

**Comment by anthonyanjorin** [comment]
Please move to our viatra specific repository if this is still relevant.
