### ISSUE TITLE
Name Clashes in SearchEdge-Patterns for DEC

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#176]
The naming convention in search-edge patterns leads to name clashes when multiple edge types share the same name.

You can identify an edge type uniquely by its source class, target class and its name.
Only name and target class as done in our naming convention are not sufficient.

example:

Bar -foo-> Foo
Baz -foo-> Foo

**Comment by Arikae** [comment]
how urgent is this bug?

**Comment by erhanleblebici** [comment]
as far as I know it concerns Henshin-To-eMoflon integration as multiple edge types are called "graph" in Henshin. Deactivating DEC-Check was necessary for @SaschaEdwinZander to work with ibex-viatra.
It won't be urgent until Henshin integration relies on any kind of DEC-check

**Comment by anthonyanjorin** [comment]
This can be reopen and reconsidered when we have reimplemented filter PACs.  But then also with a test that is failing.
