### ISSUE TITLE
Flattened TGG rules should be sorted

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#179]
Currently, the flattened TGG rules do not seem to be sorted in a deterministic way.  While this has no effect on the result, it's a bit annoying when using a source code versioning system as it always flags the flattened tgg file as being changed.

I suggest you just sort the final TGG rules alphabetically?

**Comment by erhanleblebici** [comment]
Shouldn't we consider a flattened TGG file as a "derived" artifact?

**Comment by anthonyanjorin** [comment]
Yes, absolutely.  But the testsuites are currently designed in such a way that the tests can be executed and debugged without installing anything.  So there is an ibex.jar in lib and everything is checked in so there is no dependency to ibex.ide.

In general (from our experience) I think it's just a good idea to make sure that the exact same file is produced as this also improves builder behaviour.

**Comment by FStolte** [comment]
I implemented sorting of (what I assume to be) everything that might get out of order during the flattening, so hopefully this problem should be solved now.
