### ISSUE TITLE
Re-engineer CSPs and handling of attributes to leverage Democles better

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#186]

**Comment by anthonyanjorin** [comment]
Currently the pattern matcher knows nothing about attribute conditions and collects and maintains potentially too many matches.  

Ibex filters these matches by evaluating attribute conditions separately for each found match. 

It would be great to establish our current set of attribute conditions as actual constraints (with operations) for the incremental pattern matcher, and also to streamline this process so end users can also add their own new attribute conditions with reasonable effort.

The „old“ attribute conditions were implemented in Java and were compatible with a very early version of the Democles code generator.

**Comment by gervarro** [comment]
To introduce new constraints and operations, all phases in the Democles pattern matcher have to be appropriately configured. As I mentioned in my e-mail, relational constraints are good candidates for being a simple and similar example.

1. **EMF-based pattern specification**: `RelationalTypeModule` (https://github.com/eMoflon/emoflon-ibex-democles/blob/21de0f85445ed468198ca1f8425d490f6b052c5e/org.emoflon.ibex.tgg.runtime.democles/src/org/emoflon/ibex/tgg/runtime/engine/DemoclesEngine.java#L416) supports the use of constraints in the EMF-based pattern specification, and it is responsible for converting them to the appropriate constraints in the (modeling framework independent) pattern specification.
2. **(Modeling framework independent) pattern specification**: The `CoreConstraintModule` (also in https://github.com/eMoflon/emoflon-ibex-democles/blob/21de0f85445ed468198ca1f8425d490f6b052c5e/org.emoflon.ibex.tgg.runtime.democles/src/org/emoflon/ibex/tgg/runtime/engine/DemoclesEngine.java#L416) supports the use of constraints in the main pattern specification. Relational constraints (i.e., without adornments) are simply placeholders in the first two phases. (EMF-related constraints are somewhat more complex, as a new constraint is created for each `EReference` and `EAttribute` in the metamodels.) The corresponding switches are added to the `EMFPatternBuilder` at https://github.com/eMoflon/emoflon-ibex-democles/blob/21de0f85445ed468198ca1f8425d490f6b052c5e/org.emoflon.ibex.tgg.runtime.democles/src/org/emoflon/ibex/tgg/runtime/engine/DemoclesEngine.java#L422.
3. **Runtime operation**: The `RelationalOperationalBuilder` (https://github.com/eMoflon/emoflon-ibex-democles/blob/21de0f85445ed468198ca1f8425d490f6b052c5e/org.emoflon.ibex.tgg.runtime.democles/src/org/emoflon/ibex/tgg/runtime/engine/DemoclesEngine.java#L436-L437) specifies how relational constraints are mapped to the corresponding operations that can be executed at runtime. The operations contain the real implementation, i.e., how to check, e.g., an `A < B` constraint. These are the classes that have to be manually implemented or automatically generated in your setup. If you look at some of the subclasses of `NativeOperation` or `InterpretableAdornedOperation`, you will easily understand the concept. A `NativeOperation` can be connected to several `DelegatingAdornedOperations` if different adornments are allowed for a certain `NativeOperation`. The `InterpretableAdornedOperations` only allow a single adornment to be specified like for relational operations. `BB`. There is one additional critical difference between the `NativeOperation` + `DelegatingAdornedOperation` combination vs. `InterpretableAdornedOperation`, namely, the first combination can feed new match events into the Rete network, while a typical `InterpretableAdornedOperation` simply performs a check on an existing match. Currently, I have the impression that all your planned operations (even the ones that extend the match) might fall into the second category. However, it is not really time consuming to perform the conversion between the two options.
4. **Handling of operations in the Rete network construction (incremental search plan) phase**: The `FilterComponentBuilder` (https://github.com/eMoflon/emoflon-ibex-democles/blob/21de0f85445ed468198ca1f8425d490f6b052c5e/org.emoflon.ibex.tgg.runtime.democles/src/org/emoflon/ibex/tgg/runtime/engine/DemoclesEngine.java#L445) simply creates a `FilterComponent` for each relational constraint occurring in the pattern specifications. A `FilterComponent` represents a Rete subnetwork that is used at runtime to "filter" the matches, although the name is not completely precise, as a better description would be that a clearly batch operation is carried out on an incremental match event flow (i.e., no new match events are fed into the Rete network at relational operations) [reapply batch attribute calculations when something incrementally changes].

Short summary: Implementing the first two steps should be trivial in your case as well. The real filtering operations (i.e., with `BB` adornment) can be implemented in exactly the same way as the relational operations in both the third and the fourth steps. The only question (which might require some experimentation) is what to do with result producing operations like `A = B + C` (e.g., with `FBB` adornment), but my current idea is to handle them with the appropriate adornment in the same way as you would do in the batch case, and to use `FilterComponent` in the fourth step.

(Btw. if you want to use attribute calculations in a batch interpreted mode, then you have to implement a step that is similar to 4 for the batch search plan algorithm (but steps 1-3 are identical). If you want to have attribute calculations in generated code, then steps 1-2 are identical and you have to replace the runtime operation with the appropriate modules and you can use the same search plan generation module for the batch interpreted and the batch compiled case.)

**Comment by gervarro** [comment]
The source code for Democles is available in the installed plugins, and you can extend Democles without changing a single line in the existing code, but if you really need Democles in your Eclipse workspace, then:

1. Install Eclipse Utils from the http://gervarro.org/eclipse-utils/integration-2.0.0/ update site.
2. Install Apache Ivy from the http://www.apache.org/dist/ant/ivyde/updatesite update site.
3. Change the run configuration for the build.xml files in the corresponding feature projects (`org.gervarro.democles.feature.specification`, `org.gervarro.democles.feature.interpreter`) as follows: (a) add the ivy plugin in the Classpath tab, (b) select "Run in the same JRE as the workspace" in the JRE tab, (c) select "feature.init" in the Targets tab.
4. Run the "feature.init" target for both feature projects. It should create all the missing files in the plugin projects constituting Democles. If it does not work, then give a try with the `-Dtransitive=true` argument.

I am planning to switch to Gradle in the future, but I did not have to time yet to carry out this move.

**Comment by anthonyanjorin** [comment]
Hi Greg,

We’ve been able to implement (1) and (2) and feel that these steps are pretty clear.

Concerning (3) and (4) we first of all tried using InterpretableAdornedOperations but only the BB case works with that.  The problem as we can see it is that the FilterComponentBuilder ignores all other possible adornments.  For cases like FF or FB we thus get „No Search Plan found“ exceptions. 

We are indeed wondering if this solution makes sense...  our constraints can extend matches and can decide if the current partial match is invalid or if it can be completed to a match.  

We are currently trying the other approach using NativeOperations but haven’t got this running yet as we do not really know how to specify a component builder for this case.  We are currently working on it.

Could you perhaps explain how using the first approach could work for cases like FB?  Note that an extra variable is added to the pattern which is bounded by the operation.  Do you expect us to create a new frame in such cases?  We were very unsure about that.

@Arikae could you provide links to our code on the csp branch?

Thanks,
Tony

**Comment by gervarro** [comment]
Hi Tony,

> Concerning (3) and (4) we first of all tried using InterpretableAdornedOperations but only the BB case works with that. The problem as we can see it is that the FilterComponentBuilder ignores all other possible adornments. For cases like FF or FB we thus get „No Search Plan found“ exceptions.

Replace the `FilterComponentBuilder` with your own implementation that returns a `FilterComponent` for each `InterpretableAdornedOperation` (and not only for adornments with 0 cardinality). You can copy-paste the builder and change the copied code however you like.

> We are currently trying the other approach using NativeOperations but haven’t got this running yet as we do not really know how to specify a component builder for this case. We are currently working on it.
>
> Could you perhaps explain how using the first approach could work for cases like FB? Note that an extra variable is added to the pattern which is bounded by the operation. Do you expect us to create a new frame in such cases? We were very unsure about that.

Please check the EMF related subclasses of the `NativeOperation` class. These subclasses are a central location for specifying behaviour for EMF reference navigation / attribute lookup for different adornments (`BB`,`BF`,`FB`). Additionally, an `InterpretedAdornedOperation` (or an instance of one of its subclasses) has to be prepared for each pair of `NativeOperation` and adornment, so for a bidirectional edge there is one `NativeOperation` and 3 `DelegatingAdornedOperations` (a subclass of `InterpretedAdornedOperation`). You can check the EMF-related builders as well to get an idea how it works. In your case, I could imagine a `NativeOperation` subclass for each arithmetic operation, and a `DelegatingAdornedOperation` for each adornment. There are some `AdornmentAssignmentStrategies` in the code that actually defines the adornments for a certain `NativeOperation` subclass.

An extend operation (i.e., with at least `F` letter) must create a new frame (see the corresponding `createDataFrame()` method in the `NativeOperation` class, or the specification in the `org.gervarro.democles.interpreter.InterpretableOperation` interface). You can also check the existing implementations for EMF related stuff (like `BidirectionalManyToOneOperation`, which covers all the cases).

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Thanks for the fast reply!  The trick was to add as many components as required.  Things seem to be working now using native operations.

**Comment by anthonyanjorin** [comment]
I'm closing this now as @Arikae has opened multiple more specific issues.
