### ISSUE TITLE
Faulty generation of NACs for container constraints

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#201]
The pattern ``ConnectFather__MODELGEN`` in ``testsuite1_familiestopersons`` is wrong as it only has a NAC for the ``father`` connection between ``fm`` and ``f``.

The relevant application condition should be, however, that fm should not be contained in anyway in any container (as it would hop out of its container and be placed in ``fm``).

The forbidden edge should therefore be ``container:EObject <--eContainer-- fm:FamilyMember`` instead of ``f:Family --father--> fm:FamilyMember``.

Btw:  it would be nice to have a test case that fails due to this error.

**Comment by FStolte** [comment]
Unfortunately, creating a failing test case is not possible with our current meta-models. The current implementation of containment constraints works correctly for the special case that an object can only be contained by one other type (in this case only a Family can contain a FamilyMember). To test the case where this constraint fails, we would need a meta-model where an object can be contained by two different types.

Nevertheless, I will have a look into this.

**Comment by anthonyanjorin** [comment]
@FStolte Now that Greg has implemented the new constraint type we should discuss how best to use it in the analysis.  IbexPatterns should remain engine independent, but we need some way to represent this edge type so it can be either supported by engines or ignored if they cannot.
