### ISSUE TITLE
CC: NullPointerException on some Tests

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex#202]
Hi Erhan,

I just wrote a few tests using the `modelsAreConsistent()` method and I am getting `NullPointerExceptions` for some of them. The exceptions occur in the `ConsistencyReporter` during `extractInconsistentEdges()`. The innermost if-statement does not cover the case that `getterResult` is null; adding this check removes the Exceptions. However, since I am not sure what it means if there is a null reference in this situation, it might be better if you have a look at it. The test cases causing the Exceptions are in the project `testsuite1_familiestopersons` under `test/testsuite1.familiestopersons.cc/`.

Best Regards,
Florian

**Comment by erhanleblebici** [comment]
Hi Florian, 
your solution seems just correct. I really did not think about the case where the getter returns null. 
Null means that there is no edge to be reported, so a null check is all what you need.
You can surely commit your solution
