### ISSUE TITLE
Add documentation to our ecore metamodels

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#223]
I just figured out how to add generated Javadoc to an ecore metamodel:

1.  Add an EAnnotation as a child of the element to be documented
2.  Set the source of the annotation as ```http://www.eclipse.org/emf/2002/GenModel```
3.  Add an entry to the annotation with its ```Key``` set to ```documentation```, and its ```value``` the actual text to be generated as a JavaDoc comment.

It would be nice to do this for all our metamodels.

**Comment by Arikae** [comment]
Done
