### ISSUE TITLE
New constraint type for ---eAllContents-->

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#239]
Hi Greg,

while trying to make use of our --eContainer--> edge, I just realised that to create a green containment edge safely, we also have to ensure that the rule application does not create a containment cycle.

Would it be possible to have a special --eAllContents--> edge similar to the solution for #201?

Cheers and thanks!
Tony

**Comment by gervarro** [comment]
Hi Tony,

if I remember correctly, containment cycles are checked automatically by EMF, when you create a new containment edge. Please check it in the generated code. If I am right, then I would use the standard feature.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
I don't know why, but I can say with certainty that this doesn't work for dynamic EMF (no generated code), we just get an endless loop until a stack-overflow is eventually thrown after a long time.

My guess with generated code is perhaps that the cycle will just be broken by kicking out the element just being added as a child (so similar to trying to add a second container).

Our model generator should sort out these matches and not even try to apply such rules (an exception would be just as bad).
