### ISSUE TITLE
UserDefinedRuntimeTGGAttrConstraintFactory prevents projects with multiple TGGs where at least one has custom constraints

### ISSUE THREAD

**Issue by FabianMarcoBauer** [eMoflon/emoflon-ibex#241]
Since all factories are located at org/emoflon/ibex/tgg/operational/csp/constraints/factories/UserDefinedRuntimeTGGAttrConstraintFactory, the default classloader only loads one of them and drops the others.

**Comment by anthonyanjorin** [comment]
Up until now, we have always had the convention of having exactly one TGG per (Eclipse) project.  Is this what you are trying out?  Many things won’t work including the stub (Java classes with main methods) generation.

Do you have to have multiple TGGs in one project or could you just split up the project into one project per TGG?

**Comment by FabianMarcoBauer** [comment]
I didn't mean developing two tggs in one project, but using multiple tggs as libraries in a third project. Like for example in https://github.com/emoflon/emoflon-ibex-tests .

**Comment by anthonyanjorin** [comment]
Ok - now I get it.  @Arikae Can this be fixed easily and without breaking all existing stubs to badly?  We had this problem with the generated stubs as well and the solution was to integrate the name of the TGG project in the package path.

**Comment by Arikae** [comment]
Is this still a problem? 
Then how did we solve it in emoflon-ibex-tests?

**Comment by anthonyanjorin** [comment]
Yes it's still a problem. No idea - but that's what the issue is here for.

**Comment by FabianMarcoBauer** [comment]
As far as I can tell, all tggs currently used in emoflon-ibex-tests don't have UserDefinedRuntimeTGGAttrConstraints. In this case it does not matter which Factory is loaded.
But as soon as a new tgg with UserDefinedRuntimeTGGAttrConstraint is added, a  `java.lang.RuntimeException: CSP <name> not implemented` will be thrown during the transformation, if the loaded factory is not from the new tgg.

As a workaround, the generated Factory can be copied to another location and added from there. But this has to be repeated every time a user defined attribute condition is added or renamed.

**Comment by anthonyanjorin** [comment]
@Arikae How does this change after our latest work and changes on the CSP branch?  You had to "fix" all tests right?  Perhaps this was already a solution to this problem?

**Comment by Arikae** [comment]
This should still be a problem and I guess this issue is related to #245 .
When I move the UserDefinedRuntimeTGGAttrConstraintLibrary to gen, I can also rename the namespace to contain the project name (similar to our runtime stubs).
This should solve the issue.
