### ISSUE TITLE
Generate type check patterns for green elements

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#25]
this won't be trivial as the current code generation for (negative) pattern invokations is not really designed for that

**Comment by anthonyanjorin** [comment]
What do you mean exactly?  Why should this be problematic?

**Comment by anthonyanjorin** [comment]
Is this still open?

**Comment by erhanleblebici** [comment]
yes still open. Either the pattern matcher provides a language construct in the future, or we have to generate complex patterns which check type of an object like **(obj instanceof Subtyp1) or (obj instance of Subtyp2) or.....** and negatively invoke it

**Comment by anthonyanjorin** [comment]
ok, I'm for generating such NACs

**Comment by erhanleblebici** [comment]
implementing this in manipulation code (i.e., rejecting a match if type check fails) is much more easier (I think only one line) than generating patterns.

**Comment by anthonyanjorin** [comment]
Ahh - because this is all "interpreted" right?  Yes, that is probably true (but the wrong matches will still be collected, maybe we could check the impact of this in a BA or similar).
