### ISSUE TITLE
MarkedPatterns are invoked twice (positive and negative invocation) for each node from invoking pattern 

### ISSUE THREAD

**Issue by smilicas** [eMoflon/emoflon-ibex#253]
The problem occurs in case when node1 from patternA negatively invokes markedPattern, and node2 from patternA positively invokes markedPattern. Then, both of nodes (node1 and node2) get positive and negative invocations.

After debugging we established that the double invocations are created during translation of Ibex pattern to Democles structure.
class: "DemoclesEngine",  code line: 215

This happens probably due to workaround for variables mapping between the patterns.

**Comment by anthonyanjorin** [comment]
This should be fixed now, please check @smilicas 
BTW:  I had to ignore one MA test that is now throwing an exception.
