### ISSUE TITLE
Creation of CorrPattern and call from WHOLE Pattern

### ISSUE THREAD

**Issue by NilsWeidmann** [eMoflon/emoflon-ibex#256]
Exception "Could not initialize class" at org.emoflon.ibex.tgg.compiler.TGGCompiler.getFactory(TGGCompiler.java:79) occurs several times when executing TestSimplePositive of the TGG CompanyToIT.

**Comment by anthonyanjorin** [comment]
Hi Nils,

the problem is that what exactly "signature" and "body" nodes/edges are is quite confusing and a bit chaotic at the moment.

I'll have to clean this up a bit on master first, before we can then try out integrating CorrPattern in WHOLE again.

I'm on it!

**Comment by anthonyanjorin** [comment]
My results (just for my refactoring plans):

1.  Our signatures are actually just nodes.  The code currently hides this a bit and makes things more complex then they should be.  I’ve been able to clean this up.
2.  It makes sense to have signature nodes, local nodes, and local edges.  All these sets should be disjunct and this should be enforced in code.  Easier said than done as this is currently very chaotic.
3.  To accomplish (2) I need to clean up and simplify all patterns.  There has been a lot of hacking concerning how and when local and signature nodes are determined, and this prevents any refactoring.
