### ISSUE TITLE
Pattern refactoring:  SYNC patterns

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#258]
Please refactor all patterns under /sync to use the new IbexBasePattern instead of IbexPattern.

Take a look at all other patterns without deprecation warnings to see how this is to be done (now largely convention-based).

**Comment by Arikae** [comment]
I refactored all sync pattern except Complement*Rule. 
The code in those classes looks a bit confusing because isSignatureElement throws exceptions which is not very intuitive.
