### ISSUE TITLE
TGG Editor should warn when TGG projects (schema) break the convention for the corr model

### ISSUE THREAD

**Issue by NilsWeidmann** [eMoflon/emoflon-ibex#261]
Prefix "Benchmarx" is missing for correspondence model

**Comment by anthonyanjorin** [comment]
@NilsWeidmann Could you commit and push the fix for the BenchmarxFamiliesToPersons project?

**Comment by anthonyanjorin** [comment]
A warning should be generated by the editor if the name of the schema differs from the name of the TGG project.  While this is possible, we rely on this naming convention here and there, e.g., wrong corr models are generated.

**Comment by LegionaryCohort** [comment]
I take it the "name of the schema" is the name that is specified in the org.emoflon.ibex.tgg.Schema.tgg of a TGG project, preceded by the "#schema" keyword?
And this name should match the name of the TGG project that Schema.tgg file is contained in?

**Comment by NilsWeidmann** [comment]
Yeah, that's correct.

**Comment by anthonyanjorin** [comment]
@LegionaryCohort Have you found out what happens when this condition is violated?  I’m not sure this issue is still relevant and I can’t remember what goes wrong when the names differ (also important to decide if this is to be a warning or error).

**Comment by LegionaryCohort** [comment]
So far I've tested this by renaming the schema in one of the test-projects to mismatch the project name.
As far as I can tell everything still works fine. It still generates models that look correct and doesn't complain about anything along the way.
Can't be sure that I'm not overlooking anything though. I'll try and see what happens with a few other projects.

**Comment by anthonyanjorin** [comment]
According to my previous comment, generated correspondence models appear to be affected (I suppose they rely on the naming convention — name and location of the correspondence metamodel — to type correspondence links)

**Comment by anthonyanjorin** [comment]
Any further progress?  Have you now been able to reproduce?

**Comment by LegionaryCohort** [comment]
Yes, sorry, I've been able to reproduce the error. Forgot to reply since then, currently working on producing a sensible error-message for this problem.

**Comment by LegionaryCohort** [comment]
I've been successful in adding an error message that is displayed when the schema name and project name mismatch. However, I don't know how to limit this error to the line containing the schema name. As it stands, the entire file is marked red. Is there some way to get a reference to an EStructuralFeature that only represents the single line containing the name definition?

**Comment by anthonyanjorin** [comment]
Hi @LegionaryCohort 

are you in the context of an xtext editor?  If yes then you could just check how other error messages are located correctly in the file.

If not then I guess you're creating the problem marker yourself?  I believe the API takes a line or so.  To get this line you would have to use a regexp or similar on the file (as a string) and guess the line.

Could you provide some more info how you're creating the error marker?

Cheers,
Tony

**Comment by LegionaryCohort** [comment]
The error is created through the TGGValidator. I've simply added an additional check that takes a TGG-file and, if `schema!=null`, checks the name against the project's name (using `file.eResource().URI` to determine the project the file belongs to).

**Comment by anthonyanjorin** [comment]
Ok - so you mean this here right?  https://github.com/eMoflon/emoflon-ibex-ui/blob/master/org.emoflon.ibex.tgg.editor/src/org/moflon/tgg/mosl/validation/TGGValidator.xtend

Then it should be pretty easy:

the error method provided by Xtext is invoked with `error(message, eObj, structuralFeature, id)`

In your case the eObj is perhaps TripleGraphGrammarFile and structural feature FILE_SCHEMA or so?

**Comment by LegionaryCohort** [comment]
I'm currently invoking the `error` function like such:
`error(
					"The schema name must match the project name.",
					TggPackage.Literals.TRIPLE_GRAPH_GRAMMAR_FILE__SCHEMA,
					TGGValidator.SCHEMA_NAME_DOES_NOT_MATCH_PROJECT_NAME
				)`

This places the error at the correct line, but marks all subsequent lines red as well. While this technically fulfills the requirements of this issue, it's rather ugly.

**Comment by anthonyanjorin** [comment]
Hmm...  don't you have to specify the eObject as well?  I think the error method can take 4 parameters.

**Comment by LegionaryCohort** [comment]
This compiles and works perfectly fine (and other checks use the method the same way), but there is also the option for specifying an eObject. Not sure what to put there though, specifying the TGG-file itself (unsurprisingly) doesn't change anything.

**Comment by anthonyanjorin** [comment]
ahh... how about trying to "navigate" to the name of the schema?  So SCHEMA_NAME instead of FILE_SCHEMA?

**Comment by anthonyanjorin** [comment]
See how this is done in `def checkForUniqueNames(NamedElements ne)`

**Comment by anthonyanjorin** [comment]
That should do the trick:  you want to underline the *name* of the file

**Comment by LegionaryCohort** [comment]
Since SCHEMA_NAME doesn't directly exist (because the NAME attribute is inherited from NAMED_ELEMENT), I'm not sure how to navigate to the appropriate element. I'll see if I understand how this is done in `checkForUniqueNames` and get back to you.

**Comment by anthonyanjorin** [comment]
I think `TggPackage.Literals.NAMED_ELEMENTS__NAME` should just work

**Comment by LegionaryCohort** [comment]
It doesn't unfortunately, I just tried that. It just causes an error for the Validator.
Which I guess makes sense though, because how would it know which NamedElement is being referred to as the source of the error?

**Comment by LegionaryCohort** [comment]
I'm thinking in order to get the correct line marked, I need to step through all the NamedElements in the TGG-file and then pick the one that is the actual Schema. Then I can use that element as the source and specify NAMED_ELEMENTS__NAME as the structural reference.
Really feels like a workaround though, there must be a more direct way to get to the name attribute of the Schema...

**Comment by anthonyanjorin** [comment]
just grab the schema from the file?  file.getSchema() as eObject to the error method?

**Comment by anthonyanjorin** [comment]
(you need to use the four parameter version of the error method)

**Comment by LegionaryCohort** [comment]
Ok, I am most definitely in need of a break. That was way too obvious...
Works like a charm now.

How do I commit my changes to the repository? Is there any specific procedure/guidelines/whatever, or do I just push my changes as I would with any other project?

**Comment by anthonyanjorin** [comment]
YAY!!!  

1.  You create a new branch and commit your changes to it (name the branch sensibly and be careful not to lose your changes).  Push the branch to GitHub.
2.  You create here in GitHub a pull-request from your branch to master and assign me as responsible or whatever
3.  That's it (I'll eventually get to merging all open pull-requests)

**Comment by LegionaryCohort** [comment]
Ok, assuming I didn't screw anything up, the changes should be online with a review requested from you.
I'll leave this issue open until you've had a chance to look at my changes and merge them.
