### ISSUE TITLE
Handle non-progressive TGGs by not applying Ignore Rules at all

### ISSUE THREAD

**Issue by NilsWeidmann** [eMoflon/emoflon-ibex#290]
Tests which should pass then:

TestClassInhHier2DB - TestBWD_OPT
TestClassInhHier2DB_MA - TestBWD_OPT
TestClassMultiInhHier2DB_MA - TestBWD_OPT
TestFamiliesToPersons_MA - TestBWD_OPT

**Comment by anthonyanjorin** [comment]
The function to check for this must exist already. After all, SYNC must handle this.

**Comment by NilsWeidmann** [comment]
Yes, but it apparently does not work in FWD/BWD OPT, does it?

**Comment by anthonyanjorin** [comment]
Now it does :)
