### ISSUE TITLE
Non-injective match is found 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#309]
Run the attached GT project as a JUnit testsuite.  One of the tests will fail.  The sysouts show that the match is (as far as I can tell) non-injective but is still reported as a match.

[nonInjectiveMatchBug.zip](https://github.com/eMoflon/emoflon-ibex/files/1838998/nonInjectiveMatchBug.zip)

**Comment by anthonyanjorin** [comment]
And?  Any experiments yet?  I’m very intrigued...  :)

**Comment by anthonyanjorin** [comment]
@patrickrobrecht You can ignore the attachment.  I just added my set of tests for the lecture to our testsuite (and updated the PSF).  You now have access to the new respository so you can migrate my code/tests after API changes.

**Comment by patrickrobrecht** [comment]
I can confirm that the generation of injectivity constraints has a bug: If the two classes are different, no injectivity constraint is generated. If one is the super class of the other, there should be an injectivity consraint in the IBeXPatterns, resulting in an unequal constraint in Democles.

**Comment by patrickrobrecht** [comment]
https://github.com/eMoflon/emoflon-ibex-ui/pull/72 should solve the issue.
