### ISSUE TITLE
***App generation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#313]
I just tried out the latest state (which might not yet be finished ok..):

- I have compilation errors in my generated App due to wrong imports such as 
```
import businessrules.businessrulesPackage;
```

The b in businessrulesPackage has to be capitalised but is not.

A second point is that I would suggest making everything in ***App protected.  This class is basically a stub that the user can use to start with.  But it should leave everything open for configuration and changes.  You cannot know what the user might want to configure and why.

**Comment by anthonyanjorin** [comment]
Btw.  even after correcting the imports by hand I still couldn't get anything running as I was unable to set the workspace path for Democles.  The problem is that IContextPatternInterpreter provides the method createAndPrepareResourceSet but your generated **App does not use this method :(

And everything is private so I couldn't override anything.

**Comment by patrickrobrecht** [comment]
https://github.com/eMoflon/emoflon-ibex/pull/314 corrects the imports and makes the variables `protected`.

I don't use `createAndPrepareResourceSet` for anything - and the tests and the following example are working fine:
```
public class MySimpleFamilesApp extends SimpleFamiliesGraphTransformationApp {

	public void start() throws IOException {
		this.loadModel(URI.createFileURI("./instances/Test.xmi"));
		this.createModel(URI.createFileURI("./instances/Test2.xmi"));

		SimpleFamiliesGraphTransformationAPI api = this.initAPI(new DemoclesGTEngine());
		api.createRegister().apply();

		this.saveResourceSet();
	}

	public static void main(String[] args) throws IOException {
		new MySimpleFamilesApp().start();
	}
}
```

The `OperationalStrategy` seems to be the only user of this method. To be honest, I haven't understood why the engine has a method for creating a resource set.

**Comment by anthonyanjorin** [comment]
Simple answer:  everything you do as well and in addition, platform:/resource is mapped to the workspace path.

If you try to use platform:/resource/Foo/instances/Test1.xmi your test won’t work.

platform:/resource URIs are sometimes preferred to relative URIs as they are „absolute“ with respect to the workspace root.

So either you perform this mapping in your helper/API as well and we remove the method from the context interpreter interface, or we use the registered engine to supply a resource set all the time.
