### ISSUE TITLE
GT API:  consider renaming rule to createRule

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#326]
the api call `api.rule()` does not return a singleton but creates a new instance of the rule every time.  This is important for subscription etc so it might be better to hint at this by using `api.createRule()` instead.

**Comment by patrickrobrecht** [comment]
But what if the rule's name in the editor specification starts already with `create` or `delete` etc.? Then this convention sounds weird as it could lead to names such as `createCreateFamily()` or `createDeleteFamily()` for editor rules `createFamily` and `deleteFamily`.

**Comment by anthonyanjorin** [comment]
Hmm...  interesting aesthetic point ;)

Our options:
1.  Live with it
2. Use `newInstanceOfXXX`
3. Use `newXXX`
4. Use `createInstanceOfXXX`

You can choose whatever you prefer as long as it contains `new` or `create` in it.

**Comment by patrickrobrecht** [comment]
Doesn't option 3 can lead to weird names as well if a user names a rule `newSomething` (in the API: `api.newNewSomething()`)?

**Comment by anthonyanjorin** [comment]
Well...  I would say that users should go for verbs, i.e., `createFoo` or `findFoo` instead of `newFoo`.
New sounds like a constructor invocation of some kind and that fits quite ok.

**Comment by patrickrobrecht** [comment]
In our evaluation with end-users nobody named this as a problem. Users of the API will have to read at least a little of the documentation anyway.
