### ISSUE TITLE
TGG build: Can cause NullPointerException

### ISSUE THREAD

**Issue by patrickrobrecht** [eMoflon/emoflon-ibex#335]
The TGG build may cause a `NullPointerException`.

Example when importing the PSF for the [sokoban-final-solution branch](https://github.com/eMoflon/emoflon-ibex-examples).

![Screenshot](https://user-images.githubusercontent.com/12370952/39934965-0c896566-5537-11e8-9ee8-637b38182d60.png)

**Comment by filipgia** [comment]
Can't reproduce the bug.
