### ISSUE TITLE
minimumNumberOfEdgesToCreateEdgePatterns optimizer takes value less than 2

### ISSUE THREAD

**Issue by srijanighosh87** [eMoflon/emoflon-ibex#337]
The optimizer minimumNumberOfEdgesToCreateEdgePatterns should not take any values less than 2 while creating IbexOptions.

**Comment by anthonyanjorin** [comment]
@NilsWeidmann I suppose any value <= 2 is senseless correct?  I suggest you throw an IllegelArgumentException right in IbexOptions.

**Comment by anthonyanjorin** [comment]
Btw. I wonder if we should have an automatic max for extremely large patterns, say with over 15 edges.

**Comment by anthonyanjorin** [comment]
Can we close this now? @NilsWeidmann
