### ISSUE TITLE
Ease usage of OPT strategies via generation of automatic reg code

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#340]
Currently I don't use the OPT apps because I need to write different registration code and this is an extra hurdle :(

As we have to operate directly and only on .ecores, we could actually generate the registration code 100% automatically for these ops based on the import statements from the editor (at least when they reference .ecores).  This would considerably reduce the initial effort for using the OPT operations!

**Comment by patrickrobrecht** [comment]
Note that this is actually implemented for the GT part. If the path to the Package class cannot be derived automatically the user needs to add an import mapping to a properties.xmi file.
