### ISSUE TITLE
Custom condition could not resolved

### ISSUE THREAD

**Issue by rjulius-hsu** [eMoflon/emoflon-ibex#367]
Hi,
I’m trying to use an own attribute condition. I have defined my condition in the Schema.tgg and can find the corresponding Java class in the package **org.emoflon.ibex.tgg.operational.csp.constraints.custom**. Within my TGG-Rule the Condition couldn't resolve reference to AttrCondDef and if I try to build my project I receive the following Error: **ERROR [transformation.EditorTGGtoFlattenedTGG::75] - Unable to flatten org.moflon.tgg.mosl.tgg.impl.TripleGraphGrammarFileImpl@7426b576**

The same procedure works under eMoflon::tie. Is there something I forgot?

**Comment by anthonyanjorin** [comment]
Are you sure you used the keyword #userdefined for your new attribute condition?
Please post the declaration of your attribute condition here (from your Schema.tgg).

**Comment by rjulius-hsu** [comment]
Here it is:
#userDefined
conActionSimple(modus: EInt, conStep: EString,  conDeactStep: EString, StepId: EInt,  saType: storedActionType, timeType: timeConType){
	#sync: [B B B B B B], [F F F F F F]
	#gen: [B B B B B B ], [F F F F F F]
}

But it also doesen't work with a simple conditions:
#userDefined
test(a: EString){
	#sync:[B]
	#gen:[B]
}

**Comment by anthonyanjorin** [comment]
Could you upload a minimal  example (zip) that still doesn’t work?  I’m having problems reproducing this.

**Comment by anthonyanjorin** [comment]
Did you create your TGG rule with the new TGG rule wizard?

To resolve the attribute condition you need the following directive as the first statement in your TGG file:
```
#using <SchemaName>.*
```
E.g., the following minimal rule works for your example:
```
#using Foo.*
#using AttrCondDefLibrary.*

#rule MyRule #with Foo

#attributeConditions {
	test("foo")
}
```

If that doesn't help then I would need a minimal example to reproduce the problem.

**Comment by rjulius-hsu** [comment]
Now it works. My fault was an incorrect SchemaName. Thanks a lot!!
