### ISSUE TITLE
Establish an interface for monitoring/reporting/interacting with our operations

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#378]
Perhaps similar to IProgressMonitor in Eclipse?
An implementation of this should simply calculate and collect all kinds of statistics for the execution including:
- the size (# of nodes and edges) of all input and output models?
- memory consumption?
- runtime of different phases?
- number of matches found for each pattern?
- size of generated patterns?
- size of the TGG?
- ...

**Comment by anthonyanjorin** [comment]
Any first ideas on this issue?

**Comment by Arikae** [comment]
I'm not familiar with IProgressMonitor but wouldn't it suffice to create a Logger that is accessible and configurable through our IbexOptions?
Then our control algorithm should almost everywhere have access to the Logger.

Currently, we can only control the logging via DEBUG, INFO, ERROR etc. but we could introduce a Logging Configuration class with different pre defined standard configurations to log, e.g., which matches are applied or how many matches have been collected etc.
We could then also combine multiple pre defined configurations together without much effort.

**Comment by anthonyanjorin** [comment]
The idea here is to generalise from logging.  We plan to eventually build a debugger and the same interface could be used here to allow user inspection (and perhaps even interaction).  The interface should define interesting points in the consistency management process where we interact with a monitor and exchange some information.
