### ISSUE TITLE
TGG Editor: Multiple attribute assignments for the same attribute

### ISSUE THREAD

**Issue by adrianmoeller** [eMoflon/emoflon-ibex#384]
Currently in TGG editor it is possible to use inplace attribute expressions to make multiple assignments or contraints (equal operator) for the same attribute of a node (see examples below).
As far as I know there is no use case for this, since refinement doesn't seem to work for inplace attribute expressions and only causes these double assignments/constraints when flattened.

Examples:
```
++foo: Foo {
  intVar := 1
  intVar := 2
}

bar: Bar {
  name == "Heinz"
  name == "Peter"
}
```

**Comment by anthonyanjorin** [comment]
Yes, this should ideally be prevented with a validation rule.  Thanks!

**Comment by adrianmoeller** [comment]
Added some validation rules for this.
