### ISSUE TITLE
Attributes (1):  Extend current TGG example in our repo to include simple "in-place" attribute assignments and constraints

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#39]
Extend our current CDToDoc TGG with in-place attribute constraints, e.g., name == "foo" in a node, and attribute assignments, e.g., name := "foo" in a node.

Everything should still work, but these in-place attribute constraints and assignments will simply be ignored.

**Comment by Arikae** [comment]
All done
