### ISSUE TITLE
Attributes (3): Handle in-place attribute constraints and assignments in our compiler

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#41]
Extend the TGG compiler as follows:  (i) in each operationalisation, attribute assignments might have to be converted to constraints (if green becomes black). (ii) for in-place attribute constraints and assignments, corresponding parts of Viatra queries should be generated.  This should be possible as only constants (EDataTypes) are allowed on the right hand part of the expression.

**Comment by Arikae** [comment]
Done
