### ISSUE TITLE
Attributes (5):  Extend Editor-TGG to internal TGG transformation to cover CSPs

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#43]
Extend the trafo so CSPs are also produced in our internal TGG models.

**Comment by erhanleblebici** [comment]
attribute constraint definitions in the editor model do not seem to be correct. Do we have a parser problem here? Below, there is an example for eq: Parameters without type and adornmets with value "["

    <attributeCondDefs name="eq">
      <params/>
      <params index="1"/>
      <allowedSyncAdornments>
        <value>[</value>
      </allowedSyncAdornments>
      <allowedSyncAdornments>
        <value>[</value>
      </allowedSyncAdornments>
      <allowedSyncAdornments>
        <value>[</value>
      </allowedSyncAdornments>
      <allowedGenAdornments>
        <value>[</value>
      </allowedGenAdornments>
      <allowedGenAdornments>
        <value>[</value>
      </allowedGenAdornments>
      <allowedGenAdornments>
        <value>[</value>
      </allowedGenAdornments>
      <allowedGenAdornments>
        <value>[</value>
      </allowedGenAdornments>
    </attributeCondDefs>

**Comment by anthonyanjorin** [comment]
Found the typo in the .xtext grammar, I'm on it...

**Comment by anthonyanjorin** [comment]
Done

**Comment by Arikae** [comment]
Done but some errors remain from previous implementation attempts (02.12.2016 by Tony)
