### ISSUE TITLE
Attributes (6):  Solve CSP and set values

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#44]
Extend handling of "green" parts of patterns (ask @erhanleblebici exactly which class does this) to first of all solve the CSP of the rule and then use the determined attribute values in the green parts.

Solving the CSP means:
1.  Sorting the constraints (ask @anthonyanjorin which classes can be taken from eMoflon).
2.  Generating some code to solve the constraints in this order (code generation is probably the easiest here as we have to access and use user implemented constraints in the workspace).
3.  Green pattern handling then takes a "csp object" of some kind with the solution, and uses these values to create the required structure.

**Comment by anthonyanjorin** [comment]
Some details:

1.  `TGGRuntimeUtil::processOperationalRuleMatch` seems the right place to which to add csp solving
2.  I would suggest simply adding an invocation `solveCSP()` that returns a data structure with the result (fulfilled/violated) and a map of variables to their determined values.  This result should then be passed on to the ManipulationUtil used to create nodes later in this method.

**Comment by anthonyanjorin** [comment]
3.   We need a `register` method in our stub, where we map implementations of constraints to the constraints used in rules.

**Comment by Arikae** [comment]
Done but TempVariables still remain unsolved. Seems like we have to kill the Democles dependency for creating a CSPSearchPlan to resolve this issue -> Future Work
