### ISSUE TITLE
Rename projects to ibex...

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#6]

**Comment by anthonyanjorin** [comment]
@erhanleblebici Could you please list the projects to be renamed and what they should be renamed to?

**Comment by erhanleblebici** [comment]
org.moflon.tgg.mosl must be replaced by org.emoflon.ibex.tgg.editor
I would keep the last segments the same

**Comment by anthonyanjorin** [comment]
Fixed with #13
