### ISSUE TITLE
find out what takes so long in builder

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#64]
my impression is that we build multiple times. This can be investigated with profiling where the number of method invocations are counted

**Comment by anthonyanjorin** [comment]
I think I've solved this problem (at least the multiple building).  I have to check if I've pushed the changes yet.

**Comment by Arikae** [comment]
Great news. What was the problem?

**Comment by anthonyanjorin** [comment]
Idiotic logic in the builder (my fault).  I've merged in a fix.  Please try it out.  My experiments revealed (unfortunately) that things haven't gotten much better.  At least we now only build exactly once, and don't react to files in /bin.   A further attempt could be to check if the newly generated files are actually different from what is already there -- and if not then *not* to save unnecessarily and trigger a build from Xtend and co.

**Comment by erhanleblebici** [comment]
even if our builder logic is improved, there are something which still takes too long. I reopen the issue :(

**Comment by anthonyanjorin** [comment]
Next attempt...  this should be a huge improvement.  Sometime in the future we will have to decompose our single Xtend file.  It simply will not scale for many tgg rules...
