### ISSUE TITLE
Design and implement support for refinements

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#67]
There are plans to support refinements by pattern invocation. I see two alternatives here:

Alternative 1: Additional restrictions on refinements: no overriding of nodes in refining rules but only enlarging the rule pattern is allowed. Then the refined rule is simply a subpattern of the refining rule.

Alternative 2: pattern invocation only on parts that are not overridden. This requires a detection of what is reused in the refining rule and what is being overridden.

Alternative 1 is easier to support (and I would prefer it) but backward compatibility is again an issue due to additional restrictions

**Comment by Arikae** [comment]
Hmmm I have some problems understanding this. Why don't we just do it as in the old version?
Put everything together into one rule where black dominates green and then do the same as we did so far with all other patterns? Am I missing something?

**Comment by anthonyanjorin** [comment]
we don't want to flatten anymore -- so refinements should be mirrored directly in the patterns if possible.

**Comment by anthonyanjorin** [comment]
Work in progress
