### ISSUE TITLE
Redesign the naming of pattern variables for attributes

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#79]
Currently, pattern variables for attributes are named like:
node.name + "_" + attrExpr.attribute.name in PatternTemplate.xtend

Two things are to do:

1) Extract this naming to a helper method (see, for example, EdgePatternNaming.java) as we can only control our name conventions if we centralize them.

2) change the naming such that it is more unlikely to come to clashes.
@anthonyanjorin how can we avoid name clashes between TGG rule variables and our internal variables? Internal variables are things like edge wrappers, protocol nodes, attribute variables in patterns. What do you think about adding _emoflonIbex suffix everywhere and forbidding this to use in TGG rules?

**Comment by anthonyanjorin** [comment]
I think adding a prefix `__`and suffix `__` is enough.  This can also be added a simple validation rule in the editor.

**Comment by erhanleblebici** [comment]
prefix _ cannot be added as it has a meaning for the pattern matcher (_ prefix means you have a 'don't care' variable which does not belong to the signature of the pattern).

We can simply add a __ suffix and forbid it in the editor

**Comment by anthonyanjorin** [comment]
damn ;)  So we need a validation rule forbidding names starting with `_` and ending with `_` (or `__`).
I think users can live with that...
