### ISSUE TITLE
Implement type specific eq constraints

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-ibex#88]
... like eq_string, eq_int, eq_double, eq_boolean.... The generic eq constraint as we had so far does not suit well to the rest. 

TODO is:

- Remove Eq.java
- remove the eq decleration when generating AttrCondDefLibrary.tgg
- Implement java classes of new type-specific constraints (like Eq_string.java)
- ensure that the new constraints are generated into AttrCondDefLibrary.tgg
- fix our only test project

**Comment by Arikae** [comment]
Done
