### ISSUE TITLE
Creating a new project leads to the following error

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#93]
``The constructor FWD(TGG, Resource, Resource, Resource, Resource) is undefined``in the generated ``Application.java``.

**Comment by erhanleblebici** [comment]
@Arikae this is related to #94 (we should avoid new constructor parameter which propagates itself througout the inheritance hierarchy).
before fixing the Application.java template,  can you comment on my suggestion in #94 ?

**Comment by Arikae** [comment]
Should be fixed
