### ISSUE TITLE
Can this be shortened?  Looks awful in code...

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#94]
``org.emoflon.ibex.tgg.operational.csp.constraints.factories.UserDefinedRuntimeTGGAttrConstraintFactory``

**Comment by erhanleblebici** [comment]
@Arikae Can you consider to register user defined constraints to our factory instead of providing new classes and constructor parameters?
For example: tggRuntimeUtil.getConstraintFactory().register("MyConstraint", MyConstraint.class)

**Comment by Arikae** [comment]
Done
