### ISSUE TITLE
Use helpful constants for strings generated in Application.java 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#95]
Would be very nice to generate constants that one can just adjust at the beginning of the file for all the strings generated in Application.java

**Comment by anthonyanjorin** [comment]
``CDToDoc`` is currently generated hard-coded in every Application.java :)

**Comment by Arikae** [comment]
Can  we remove Application.java? -> b31ab4c

**Comment by Arikae** [comment]
Probably finished since we generate those files now
