### ISSUE TITLE
Currently unable to build FamiliesToPersonsDeterministic in branch startingWithTests

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex#96]
Due to a concurrent modification exception.    I think this has something to do with the fact that I have a TGG rule only in one domain (an ignore rule).

**Comment by anthonyanjorin** [comment]
I think the tgg Editor to tgg internal model transformation must be extended to handle such cases

**Comment by anthonyanjorin** [comment]
@Arikae @erhanleblebici any plans to fix this?  I can't continue with testing

**Comment by erhanleblebici** [comment]
build problems are fixed. please start a new branch from master for testing. FamiliesToPersons is now involved in master (and needed to be fixed as well due to new interfaces of runnable classes)
